/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

// @author Afonso Uéslei e Lucas Vegini
public class Tela extends javax.swing.JFrame {

    private Controller controllerView;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.initController();

    }

    public void initController() {

        this.controllerView = new Controller();
        this.controllerView.setView(this);

    }

    public JTextArea getTextArea() {
        return this.txtAreaMalha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        btSelectMalha1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMalha = new javax.swing.JTextArea();
        tfQtdVeiculos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfVelocidadeInsercao = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        btEncerrar = new javax.swing.JButton();
        btEncerrarNow = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfVelocidaVeículos = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btStart.setText("Iniciar aplicação");
        btStart.setEnabled(false);
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        btSelectMalha1.setText("Selecionar malha");
        btSelectMalha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectMalha1ActionPerformed(evt);
            }
        });

        txtAreaMalha.setColumns(10);
        txtAreaMalha.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtAreaMalha.setRows(5);
        txtAreaMalha.setAlignmentX(30.0F);
        txtAreaMalha.setAlignmentY(30.0F);
        jScrollPane1.setViewportView(txtAreaMalha);

        tfQtdVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdVeiculosActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade de veículos");

        jLabel3.setText("Velocidade de inserção");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semáforo", "Monitor" }));

        btEncerrar.setText("Encerrar");
        btEncerrar.setEnabled(false);
        btEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncerrarActionPerformed(evt);
            }
        });

        btEncerrarNow.setText("Encerrar agora");
        btEncerrarNow.setEnabled(false);
        btEncerrarNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncerrarNowActionPerformed(evt);
            }
        });

        jLabel4.setText("Professor: Fernando dos Santos");

        jLabel5.setText("Alunos: Afonso Uéslei Böing e Lucas Ramthum Vegini");

        jLabel6.setText("Disciplina:  Desenvolvimento de Sistemas Paralelos e Distribuídos");

        jLabel7.setText("Velocidade dos veículos");

        tfVelocidaVeículos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVelocidaVeículosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEncerrarNow, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfVelocidadeInsercao)
                                .addGap(131, 131, 131)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btStart))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfQtdVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tfVelocidaVeículos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSelectMalha1))
                    .addComponent(jScrollPane1))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfQtdVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSelectMalha1)
                        .addComponent(tfVelocidaVeículos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfVelocidadeInsercao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEncerrar)
                    .addComponent(btEncerrarNow))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed

        if (tfQtdVeiculos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Número de veículos não pode ser vazio");
            return;
        }

        if (tfVelocidadeInsercao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Velocidade de inserção não pode ser vazio");
            return;
        }
        try {
            this.controllerView.iniciaSimulacao(Integer.parseInt(tfQtdVeiculos.getText()), Integer.parseInt(tfVelocidadeInsercao.getText()), (String) this.cbTipo.getSelectedItem(), Integer.parseInt(this.tfVelocidaVeículos.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor do campo de texto precisa ser númerico!");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btStartActionPerformed

    private void btSelectMalha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectMalha1ActionPerformed

        JFileChooser fileChoser = new JFileChooser();
        fileChoser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int Select = fileChoser.showSaveDialog(null);

        if (Select == JFileChooser.CANCEL_OPTION) {

        } else {
            File arquivo = fileChoser.getSelectedFile();
            this.controllerView.CriaMalha(arquivo.getPath());
            this.btStart.setEnabled(true);
            this.btEncerrar.setEnabled(true);
            this.btEncerrarNow.setEnabled(true);

        }

    }//GEN-LAST:event_btSelectMalha1ActionPerformed

    private void tfQtdVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdVeiculosActionPerformed
    }//GEN-LAST:event_tfQtdVeiculosActionPerformed

    private void btEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncerrarActionPerformed

        this.controllerView.pararSimulacao();
        this.btEncerrar.setEnabled(false);
        this.btEncerrarNow.setEnabled(false);

    }//GEN-LAST:event_btEncerrarActionPerformed

    private void btEncerrarNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncerrarNowActionPerformed

        this.controllerView.pararSimulacaoAgora();
        this.btEncerrar.setEnabled(false);
        this.btEncerrarNow.setEnabled(false);

    }//GEN-LAST:event_btEncerrarNowActionPerformed

    private void tfVelocidaVeículosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVelocidaVeículosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVelocidaVeículosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEncerrar;
    private javax.swing.JButton btEncerrarNow;
    private javax.swing.JButton btSelectMalha1;
    private javax.swing.JButton btStart;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfQtdVeiculos;
    private javax.swing.JTextField tfVelocidaVeículos;
    private javax.swing.JTextField tfVelocidadeInsercao;
    private javax.swing.JTextArea txtAreaMalha;
    // End of variables declaration//GEN-END:variables
}
